### ISSUE TITLE
http://tirtaerp.lodan/transactions/perpindahan/rute

### ISSUE THREAD

**Issue by albeth** [OpenThinkLabs/TirtaERP#442]
yg status konsumennya aktif tapi jadwal kirim= NO tetap ke transfer

**Comment by wildanm** [comment]
Ini udah dikirim ....

Memang ada yg kelewat ? Kalau ada, coba screenshot pilihannya yg mana

**Comment by albeth** [comment]
ada dan kmrn waktu i pindahin trus i ganti manual coba u cek

**Comment by wildanm** [comment]
Maksudnya, seharusnya ikut ter transfer atau tidak boleh ter transfer yg bener ?

**Comment by albeth** [comment]
harusnya tetep ke transfer karena status aktif
