### ISSUE TITLE
bisa mengatur preferensi cetak faktur : margin right, left, top, bottom dan ukuran huruf

### ISSUE THREAD

**Issue by albeth** [OpenThinkLabs/TirtaERP#461]

**Comment by wildanm** [comment]
Jalankan SQL berikut disemua instalasi Tirta ERP: 

`CREATE TABLE preferensi_cetak (id INT AUTO_INCREMENT, pref VARCHAR(100) NOT NULL, pref_value VARCHAR(100) NOT NULL, jenis VARCHAR(100) NOT NULL, satuan VARCHAR(5) NOT NULL, ui VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, created_by BIGINT, updated_by BIGINT, INDEX created_by_idx (created_by), INDEX updated_by_idx (updated_by), PRIMARY KEY(id)) ENGINE = INNODB;`

**Comment by wildanm** [comment]
Jalankan SQL berikut disemua instalasi Tirta ERP:

```
INSERT IGNORE INTO preferensi_cetak (id, pref, pref_value, jenis, satuan, ui) VALUES
(1, 'margin_top', '0',  'faktur_penagihan', 'mm', 'text'),
(2, 'margin_bottom', '0', 'faktur_penagihan', 'mm', 'text'),
(3, 'margin_left', '0', 'faktur_penagihan', 'mm', 'text'),
(4, 'margin_right', '5', 'faktur_penagihan', 'mm', 'text'),
(5, 'ukuran_huruf', '9', 'faktur_penagihan', 'pt', 'text');
```

**Comment by wildanm** [comment]
Done in Changeset: | 1447 (5104fd200528)

Jika sudah Ok, close

**Comment by wildanm** [comment]
Jalankan SQL berikut : 

` INSERT IGNORE INTO preferensi_cetak(id, pref, pref_value, jenis, satuan, ui) VALUES(6, 'ukuran_huruf_2','8','faktur_penagihan','pt','text');`

**Comment by wildanm** [comment]
Update in  Changeset: | 1448 (4e23d4228a76) 

Jika sudah Ok, close
